services:
  nextjs:
    build:
      context: .
      dockerfile: stuffnext
    env_file:
      - .env  # โหลดค่าจากไฟล์ .env
    depends_on:
      - postgres
    ports:
      - "3001:3001"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 496496
      POSTGRES_DB: stuffnext
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - nextjs
